version: '3'  # Specifies the Docker Compose file format version

services:
  student_service:  # Defines the student_service container
    build: .
    restart: unless-stopped  # Ensures the container restarts unless manually stopped
    depends_on:
      - mongo  # Ensures that the mongo service starts before student_service
    environment:
      MONGO_URI: mongodb://mongo:27017  # Environment variable specifying MongoDB connection URI
    ports:
      - "8080:8080"  # Maps port 8080 on the host to port 8080 in the container

  mongo:  # Defines the MongoDB container
    restart: unless-stopped  # Ensures the container restarts unless manually stopped
    image: mongo:4  # Uses MongoDB version 4 image
    ports:
      - "27017:27017"  # Maps port 27017 on the host to port 27017 in the container
